---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: gardener-extension-shoot-traefik
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    policy: OnDemand
    deploymentRefs:
      - name: gardener-extension-shoot-traefik
  resources:
    - kind: Extension
      type: traefik
      workerlessSupported: false
      clusterCompatibility:
        - shoot
      lifecycle:
        reconcile: AfterKubeAPIServer
        delete: BeforeKubeAPIServer
        migrate: BeforeKubeAPIServer
