//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	config "github.com/gardener/gardener-extension-shoot-traefik/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddConversionFunc((*config.TraefikConfig)(nil), (*TraefikConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TraefikConfig_To_v1alpha1_TraefikConfig(a.(*config.TraefikConfig), b.(*TraefikConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*TraefikConfig)(nil), (*config.TraefikConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TraefikConfig_To_config_TraefikConfig(a.(*TraefikConfig), b.(*config.TraefikConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_TraefikConfig_To_config_TraefikConfig(in *TraefikConfig, out *config.TraefikConfig, s conversion.Scope) error {
	// WARNING: in.Spec requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_config_TraefikConfig_To_v1alpha1_TraefikConfig(in *config.TraefikConfig, out *TraefikConfig, s conversion.Scope) error {
	// WARNING: in.Replicas requires manual conversion: does not exist in peer-type
	// WARNING: in.IngressProvider requires manual conversion: does not exist in peer-type
	// WARNING: in.LogLevel requires manual conversion: does not exist in peer-type
	// WARNING: in.Dashboard requires manual conversion: does not exist in peer-type
	// WARNING: in.HTTPEntrypoint requires manual conversion: does not exist in peer-type
	return nil
}
