apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: gardener-extension-shoot-traefik
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    admission:
      runtimeCluster:
        values:
          image:
            repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/gardener-extension-shoot-traefik
            tag: latest
      virtualCluster: {}
    extension:
      values:
        image:
          repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/gardener-extension-shoot-traefik
          tag: latest
        replicaCount: 1
        resources:
          requests:
            cpu: 30m
            memory: 128Mi
        vpa:
          enabled: true
          resourcePolicy:
            minAllowed:
              memory: 64Mi
          updatePolicy:
            updateMode: Recreate
  resources:
  - kind: Extension
    type: shoot-traefik
    workerlessSupported: false
    clusterCompatibility:
    - shoot
    lifecycle:
      reconcile: AfterKubeAPIServer
      delete: BeforeKubeAPIServer
      migrate: AfterKubeAPIServer
