apiVersion: v1
description: A Helm chart to deploy the gardener-extension-admission-shoot-traefik runtime related resources
name: admission-shoot-traefik-runtime
version: 0.1.0
sources:
- https://github.com/gardener/gardener-extension-shoot-traefik
